version: '3'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    ports:
      - 9200:9200
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
  neo4j:
    build: ./docker/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./docker/neo4j/neo4j.conf:/var/lib/neo4j/conf/neo4j.conf